### ISSUE TITLE
Week 9 tempconversion Ready for Grading

### ISSUE THREAD

**Issue by lzingg1-matc** [madisoncollege-it-programs/python-scripting-lzingg1-matc#13]
no questions

**Comment by cethenmc** [comment]
Hi, Luke.  Some good progress.  However, the conversion of 32 is running first, every time you run the tempconversion script.  For example:

0.0
Please enter a temperature:  212
100.0

This means that you did not define a main function and you did not have the if __name__ conditional in place.

I will record a 4 of 8 for now.  Respond to this Issue ticket when you have pushed corrections to GitHub, or please feel free to reach out if you need a hand.  I am happy to help.

Thanks.

Chris

**Comment by cethenmc** [comment]
I will also add that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, since you are modifying the other pieces, you may want to consider modifying your tempconversion.py script to run that way.

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/207955521-1922bbc5-80cb-4111-a0ec-c4be9a34218b.png)
